# Generated by Django 3.2 on 2023-08-10 04:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_invite_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название Вашего мероприятия', max_length=255, verbose_name='Заголовок мероприятия')),
                ('description', models.TextField(help_text='Введите подробное описание мероприятия', verbose_name='Вся информация о событии')),
                ('pubdate', models.DateTimeField(auto_now_add=True)),
                ('datetime', models.DateTimeField()),
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='users.department')),
                ('expert', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
