# Generated by Django 3.2 on 2023-08-10 07:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_invite_status'),
        ('events', '0002_auto_20230810_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, help_text='Введите адрес, где будет проходить мероприятие без указания города', max_length=255, verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.ForeignKey(help_text='Выберите город, в котором будет проходить мероприятие', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='users.department', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='event',
            name='datetime',
            field=models.DateTimeField(help_text='Введите дату в формате: дд.мм.гггг чч:мм:сс', verbose_name='Дата проведения'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(help_text='Введите подробное описание мероприятия, заранее подготовьте текст', verbose_name='Вся информация о событии'),
        ),
    ]
