# Generated by Django 3.2 on 2023-08-02 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
