# Generated by Django 3.2 on 2023-08-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_invite_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrafieldsexpert',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Загрузите Ваше фото, которое будет представлено посетителям', upload_to='avatars', verbose_name='Фото профиля'),
        ),
    ]
