# Generated by Django 3.2 on 2023-09-11 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_extrafieldsexpert_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrafieldsexpert',
            name='city',
            field=models.ForeignKey(default=1, help_text='Укажите город, в котором Вы проживаете', on_delete=django.db.models.deletion.DO_NOTHING, to='users.department', verbose_name='Город'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Skillset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.extrafieldsexpert')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.skill')),
            ],
        ),
        migrations.AddField(
            model_name='extrafieldsexpert',
            name='skills',
            field=models.ManyToManyField(help_text='Укажите направления, в которых Вы компетентны', through='users.Skillset', to='users.Skill', verbose_name='Направления Вашей деятельности'),
        ),
    ]
